os: linux
arch: amd64
dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:  
  - LARAVEL_VERSION=5.7.*
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=6.*
  - LARAVEL_VERSION=7.*
  - LARAVEL_VERSION=8.*

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  exclude:    
    - php: 7.2
      env: LARAVEL_VERSION=8.*
    - php: 7.3
      env: LARAVEL_VERSION=8.* 
    - php: 8.0
      env: LARAVEL_VERSION=5.7.*
    - php: 8.0
      env: LARAVEL_VERSION=5.8.*
    - php: 8.0
      env: LARAVEL_VERSION=6.*
    - php: 8.0
      env: LARAVEL_VERSION=7.*

before_script:
  - composer config discard-changes true
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;  
  - composer update

script: phpunit